name: Schedule Email Status Check

on:
  schedule:
    - cron: '*/5 * * * *'  # Executa a cada 5 minutos
  workflow_dispatch:  # Permite execução manual

jobs:
  check_email_status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Substitua pelo Python 3.x desejado

      - name: Install dependencies
        run: pip install requests

      - name: Run check_email_status script
        run: python check_email_status.py
