name: Schedule Insere Carrinho Abandonado Check

on:
  schedule:
    - cron: '0 */1 * * *'  # Executa a cada 1 hora
  workflow_dispatch:  # Permite execução manual

jobs:
  check_email_status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Substitua pelo Python 3.x desejado

      - name: Install dependencies
        run: pip install requests

      - name: Run check_insere_carrinho_abandonado script
        run: python check_insere_carrinho_abandonado.py
